brightmap texture COMP2
{
	map "shaders/brightmaps/doom/comp2.png"
	iwad
}	

brightmap texture COMPSTA1
{
	map "shaders/brightmaps/doom/compsta1.png"
	iwad
}

brightmap texture COMPSTA2
{
	map "shaders/brightmaps/doom/compsta2.png"
	iwad
}

brightmap texture COMPTALL
{
	map "shaders/brightmaps/doom/comptall.png"
	iwad
}

brightmap texture COMPUTE1
{
	map "shaders/brightmaps/doom/compute1.png"
	iwad
}

brightmap texture COMPUTE2
{
	map "shaders/brightmaps/doom/compute2.png"
	iwad
}

brightmap texture COMPUTE3
{
	map "shaders/brightmaps/doom/compute3.png"
	iwad
}

brightmap texture DOORYEL
{
	map "shaders/brightmaps/doom/dooryel.png"
	iwad
}

brightmap texture DOORRED
{
	map "shaders/brightmaps/doom/dooryel.png"
	iwad
}

brightmap texture DOORBLU
{
	map "shaders/brightmaps/doom/dooryel.png"
	iwad
}

brightmap texture EXITDOOR
{
	map "shaders/brightmaps/doom/exitdoor.png"
	iwad
}

brightmap texture EXITSIGN
{
	map "shaders/brightmaps/doom/exitsign.png"
	iwad
}

brightmap texture liteblu1
{
	map "shaders/brightmaps/doom/liteblu1.png"
	iwad
}

brightmap texture liteblu2
{
	map "shaders/brightmaps/doom/liteblu2.png"
	iwad
}

brightmap texture liteblu3
{
	map "shaders/brightmaps/doom/liteblu3.png"
	iwad
}

brightmap texture liteblu4
{
	map "shaders/brightmaps/doom/liteblu4.png"
	iwad
}

brightmap texture nuke24
{
	map "shaders/brightmaps/doom/nuke24.png"
	iwad
}

brightmap texture nukedege1
{
	map "shaders/brightmaps/doom/nukedge1.png"
	iwad
}

brightmap texture nukeslad
{
	map "shaders/brightmaps/doom/nukeslad.png"
	iwad
}

brightmap texture planet1
{
	map "shaders/brightmaps/doom/planet1.png"
	iwad
}

brightmap texture redwall1
{
	map "shaders/brightmaps/doom/redwall1.png"
	iwad
}

brightmap texture sladrip1
{
	map "shaders/brightmaps/doom/sladrip1.png"
	iwad
}

brightmap texture sladrip2
{
	map "shaders/brightmaps/doom/sladrip2.png"
	iwad
}

brightmap texture sladrip3
{
	map "shaders/brightmaps/doom/sladrip3.png"
	iwad
}

brightmap texture sw1brcom
{
	map "shaders/brightmaps/doom/sw1brcom.png"
	iwad
}

brightmap texture sw1comm
{
	map "shaders/brightmaps/doom/sw1comm.png"
	iwad
}

brightmap texture sw1dirt
{
	map "shaders/brightmaps/doom/sw1dirt.png"
	iwad
}

brightmap texture sw1ston1
{
	map "shaders/brightmaps/doom/sw1ston1.png"
	iwad
}

brightmap texture sw1stone
{
	map "shaders/brightmaps/doom/sw1stone.png"
	iwad
}

brightmap texture sw1strtn
{
	map "shaders/brightmaps/doom/sw1strtn.png"
	iwad
}

brightmap texture sw2brcom
{
	map "shaders/brightmaps/doom/sw2brcom.png"
	iwad
}

brightmap texture sw2brn2
{
	map "shaders/brightmaps/doom/sw2brn2.png"
	iwad
}

brightmap texture sw2brngn
{
	map "shaders/brightmaps/doom/sw2brngn.png"
	iwad
}

brightmap texture sw2comm
{
	map "shaders/brightmaps/doom/sw2comm.png"
	iwad
}

brightmap texture sw2comp
{
	map "shaders/brightmaps/doom/sw2comp.png"
	iwad
}

brightmap texture sw2dirt
{
	map "shaders/brightmaps/doom/sw2dirt.png"
	iwad
}

brightmap texture sw2exit
{
	map "shaders/brightmaps/doom/sw2exit.png"
	iwad
}

brightmap texture sw2grey
{
	map "shaders/brightmaps/doom/sw2grey.png"
	iwad
}

brightmap texture sw2grey1
{
	map "shaders/brightmaps/doom/sw2grey1.png"
	iwad
}

brightmap texture sw2metal
{
	map "shaders/brightmaps/doom/sw2metal.png"
	iwad
}

brightmap texture sw2slad
{
	map "shaders/brightmaps/doom/sw2slad.png"
	iwad
}

brightmap texture sw2ston1
{
	map "shaders/brightmaps/doom/sw2ston1.png"
	iwad
}

brightmap texture sw2ston2
{
	map "shaders/brightmaps/doom/sw2slad.png"
	iwad
}

brightmap texture sw2stone
{
	map "shaders/brightmaps/doom/sw2stone.png"
	iwad
}

brightmap texture sw2strtn
{
	map "shaders/brightmaps/doom/sw2stone.png"
	iwad
}

brightmap texture tekwall1
{
	map "shaders/brightmaps/doom/tekwall1.png"
	iwad
}

brightmap texture tekwall2
{
	map "shaders/brightmaps/doom/tekwall2.png"
	iwad
}

brightmap texture tekwall5
{
	map "shaders/brightmaps/doom/tekwall5.png"
	iwad
}

brightmap texture exitston
{
	map "shaders/brightmaps/doom/exitston.png"
	iwad
}

brightmap texture fireblu1
{
	map "shaders/brightmaps/doom/fireblu1.png"
	iwad
}

brightmap texture fireblu2
{
	map "shaders/brightmaps/doom/fireblu2.png"
	iwad
}

brightmap texture firelav2
{
	map "shaders/brightmaps/doom/firelav2.png"
	iwad
}

brightmap texture firelav3
{
	map "shaders/brightmaps/doom/firelav2.png"
	iwad
}

brightmap texture firelava
{
	map "shaders/brightmaps/doom/firelava.png"
	iwad
}

brightmap texture firemag1
{
	map "shaders/brightmaps/doom/firemag1.png"
	iwad
}

brightmap texture firemag2
{
	map "shaders/brightmaps/doom/firemag2.png"
	iwad
}

brightmap texture firemag3
{
	map "shaders/brightmaps/doom/firemag3.png"
	iwad
}

brightmap texture firewala
{
	map "shaders/brightmaps/doom/firewala.png"
	iwad
}

brightmap texture firewalb
{
	map "shaders/brightmaps/doom/firewalb.png"
	iwad
}

brightmap texture firewall
{
	map "shaders/brightmaps/doom/firewall.png"
	iwad
}

brightmap texture litered
{
	map "shaders/brightmaps/doom/litered.png"
	iwad
}

brightmap texture nukepois
{
	map "shaders/brightmaps/doom/nukedge1.png"
	iwad
}

brightmap texture sladskul
{
	map "shaders/brightmaps/doom/sladskul.png"
	iwad
}

brightmap texture sw2blue
{
	map "shaders/brightmaps/doom/sw2blue.png"
	iwad
}

brightmap texture sw2garg
{
	map "shaders/brightmaps/doom/sw2garg.png"
	iwad
}

brightmap texture sw2gston
{
	map "shaders/brightmaps/doom/sw2gston.png"
	iwad
}

brightmap texture sw2hot
{
	map "shaders/brightmaps/doom/sw2hot.png"
	iwad
}

brightmap texture sw2lion
{
	map "shaders/brightmaps/doom/sw2lion.png"
	iwad
}

brightmap texture sw2satyr
{
	map "shaders/brightmaps/doom/sw2satyr.png"
	iwad
}

brightmap texture sw2vine
{
	map "shaders/brightmaps/doom/sw2vine.png"
	iwad
}

brightmap texture sw2wood
{
	map "shaders/brightmaps/doom/sw2wood.png"
	iwad
}

brightmap texture wood4
{
	map "shaders/brightmaps/doom/wood4.png"
	iwad
}

brightmap texture woodgarg
{
	map "shaders/brightmaps/doom/woodgarg.png"
	iwad
}

brightmap texture woodskul
{
	map "shaders/brightmaps/doom/woodskul.png"
	iwad
}

brightmap flat  CEIL3_4
{
	map "shaders/brightmaps/doom/ceil3_4.png"
	iwad
}	

brightmap flat  CEIL3_6
{
	map "shaders/brightmaps/doom/ceil3_6.png"
	iwad
}

brightmap flat  CONS1_1
{
	map "shaders/brightmaps/doom/cons1_1.png"
	iwad
}	

brightmap flat  CONS1_5
{
	map "shaders/brightmaps/doom/cons1_5.png"
	iwad
}

brightmap flat  CONS1_7
{
	map "shaders/brightmaps/doom/cons1_7.png"
	iwad
}

brightmap flat  RROCK01
{
	map "shaders/brightmaps/doom/rrock02.png"
	iwad
}	

brightmap flat  RROCK02
{
	map "shaders/brightmaps/doom/rrock05.png"
	iwad
}	

brightmap flat  RROCK05
{
	map "shaders/brightmaps/doom/rrock05.png"
	iwad
}	

brightmap flat  RROCK06
{
	map "shaders/brightmaps/doom/rrock06.png"
	iwad
}			

brightmap flat  RROCK07
{
	map "shaders/brightmaps/doom/rrock07.png"
	iwad
}	

brightmap flat  RROCK08
{
	map "shaders/brightmaps/doom/rrock08.png"
	iwad
}	

brightmap flat  NUKAGE1
{
	map "shaders/brightmaps/doom/nukage1.png"
	iwad
}

brightmap flat  NUKAGE2
{
	map "shaders/brightmaps/doom/nukage2.png"
	iwad
}

brightmap flat  NUKAGE3
{
	map "shaders/brightmaps/doom/nukage3.png"
	iwad
}

brightmap flat  CEIL1_3
{
	map "shaders/brightmaps/doom/ceil1_3.png"
	iwad
}

brightmap flat  CEIL1_2
{
	map "shaders/brightmaps/doom/ceil1_2.png"
	iwad
}

brightmap flat  FLAT2
{
	map "shaders/brightmaps/doom/flat2.png"
	iwad
}

brightmap flat  FLOOR1_7
{
	map "shaders/brightmaps/doom/floor1_7.png"
	iwad
}

brightmap flat  GRNLITE1
{
	map "shaders/brightmaps/doom/grnlite1.png"
	iwad
}

brightmap flat  GATE1
{
	map "shaders/brightmaps/doom/GATE1.png"
	iwad
}

brightmap flat  GATE2
{
	map "shaders/brightmaps/doom/GATE2.png"
	iwad
}

brightmap flat  GATE3
{
	map "shaders/brightmaps/doom/GATE3.png"
	iwad
}

brightmap flat  GATE4
{
	map "shaders/brightmaps/doom/GATE4.png"
	iwad
}

brightmap flat  SLIME09
{
	map "shaders/brightmaps/doom/slime09.png"
	iwad
}

brightmap flat  SLIME10
{
	map "shaders/brightmaps/doom/slime10.png"
	iwad
}
brightmap flat  SLIME11
{
	map "shaders/brightmaps/doom/slime11.png"
	iwad
}

brightmap flat  TLITE6_1
{
	map "shaders/brightmaps/doom/tlite6_4.png"
	iwad
}

brightmap flat  TLITE6_4
{
	map "shaders/brightmaps/doom/tlite6_4.png"
	iwad
}

brightmap flat  TLITE6_5
{
	map "shaders/brightmaps/doom/tlite6_5.png"
	iwad
}

brightmap flat  TLITE6_6
{
	map "shaders/brightmaps/doom/tlite6_6.png"
	iwad
}

brightmap flat  lava1
{
	map "shaders/brightmaps/doom/lava1.png"
	iwad
}

brightmap flat  lava2
{
	map "shaders/brightmaps/doom/lava2.png"
	iwad
}

brightmap flat  lava3
{
	map "shaders/brightmaps/doom/lava3.png"
	iwad
}

brightmap flat  lava4
{
	map "shaders/brightmaps/doom/lava4.png"
	iwad
}

brightmap sprite pisfa0
{
	map "shaders/brightmaps/doom/pisfa0.png"
	iwad
		disablefullbright
}

brightmap sprite sht2i0
{
	map "shaders/brightmaps/doom/sht2i0.png"
	iwad
		disablefullbright
}

brightmap sprite sht2j0
{
	map "shaders/brightmaps/doom/sht2j0.png"
	iwad
		disablefullbright
}

brightmap sprite plsfa0
{
	map "shaders/brightmaps/doom/plsfa0.png"
	iwad
		disablefullbright
}

brightmap sprite plsfb0
{
	map "shaders/brightmaps/doom/plsfb0.png"
	iwad
		disablefullbright
}

brightmap sprite bfggb0
{
	map "shaders/brightmaps/doom/bfggb0.png"
	iwad
		disablefullbright
}

brightmap sprite BFUGA0
{
	map "shaders/brightmaps/doom/bfuga0.png"
	iwad
}

brightmap sprite CANDA0
{
	map "shaders/brightmaps/doom/canda0.png"
	iwad
		disablefullbright
}

brightmap sprite CBRAA0
{
	map "shaders/brightmaps/doom/cbraa0.png"
	iwad
		disablefullbright
}

brightmap sprite PVISA0
{
	map "shaders/brightmaps/doom/pvisa0.png"
	iwad
		disablefullbright
}

brightmap sprite PVISB0
{
	map "shaders/brightmaps/doom/pvisb0.png"
	iwad
		disablefullbright
}

brightmap sprite PMAPA0
{
	map "shaders/brightmaps/doom/pmapa0.png"
	iwad
		disablefullbright
}

brightmap sprite PMAPB0
{
	map "shaders/brightmaps/doom/pmapb0.png"
	iwad
		disablefullbright
}

brightmap sprite PMAPC0
{
	map "shaders/brightmaps/doom/pmapc0.png"
	iwad
		disablefullbright
}

brightmap sprite PMAPD0
{
	map "shaders/brightmaps/doom/pmapd0.png"
	iwad
		disablefullbright
}

brightmap sprite PLASA0
{
	map "shaders/brightmaps/doom/plasa0.png"
	iwad
		disablefullbright
}


brightmap sprite CELLA0
{
	map "shaders/brightmaps/doom/cella0.png"
	iwad
}

brightmap sprite CELPA0
{
	map "shaders/brightmaps/doom/celpa0.png"
	iwad
}

brightmap sprite COLUA0
{
	map "shaders/brightmaps/doom/colua0.png"
	iwad
		disablefullbright
}

brightmap sprite PLAYF1
{
	map "shaders/brightmaps/doom/PLAYf1.png"
	iwad
	disablefullbright
}

brightmap sprite PLAYF2F8
{
	map "shaders/brightmaps/doom/PLAYf2f8.png"
	iwad
	disablefullbright
}

brightmap sprite PLAYF3F7
{
	map "shaders/brightmaps/doom/PLAYf3f7.png"
	iwad
	disablefullbright
}

brightmap sprite PLAYF4F6
{
	map "shaders/brightmaps/doom/PLAYf4f6.png"
	iwad
	disablefullbright
}

brightmap sprite PLAYF5
{
	map "shaders/brightmaps/doom/PLAYf5.png"
	iwad
	disablefullbright
}

brightmap sprite POSSF1
{
	map "shaders/brightmaps/doom/possf1.png"
	iwad
	disablefullbright
}

brightmap sprite POSSF2F8
{
	map "shaders/brightmaps/doom/possf2f8.png"
	iwad
	disablefullbright
}

brightmap sprite POSSF3F7
{
	map "shaders/brightmaps/doom/possf3f7.png"
	iwad
	disablefullbright
}

brightmap sprite POSSF4F6
{
	map "shaders/brightmaps/doom/possf4f6.png"
	iwad
	disablefullbright
}

brightmap sprite POSSF5
{
	map "shaders/brightmaps/doom/possf5.png"
	iwad
	disablefullbright
}

brightmap sprite SPOSF1
{
	map "shaders/brightmaps/doom/SPOSf1.png"
	iwad
	disablefullbright
}

brightmap sprite SPOSF2F8
{
	map "shaders/brightmaps/doom/SPOSf2f8.png"
	iwad
	disablefullbright
}

brightmap sprite SPOSF3F7
{
	map "shaders/brightmaps/doom/SPOSf3f7.png"
	iwad
	disablefullbright
}

brightmap sprite SPOSF4F6
{
	map "shaders/brightmaps/doom/SPOSf4f6.png"
	iwad
	disablefullbright
}

brightmap sprite SPOSF5
{
	iwad
	map "shaders/brightmaps/doom/SPOSf5.png"
	disablefullbright
}

brightmap sprite CPOSE1
{
	map "shaders/brightmaps/doom/CPOSE1.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE2
{
	map "shaders/brightmaps/doom/CPOSE2.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE3
{
	map "shaders/brightmaps/doom/CPOSE3.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE4
{
	iwad
	disablefullbright
}

brightmap sprite CPOSE5
{
	map "shaders/brightmaps/doom/CPOSE5.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE6
{
	map "shaders/brightmaps/doom/CPOSE6.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE7
{
	map "shaders/brightmaps/doom/CPOSE7.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSE8
{
	map "shaders/brightmaps/doom/CPOSE8.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF1
{
	map "shaders/brightmaps/doom/CPOSF1.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF2
{
	map "shaders/brightmaps/doom/CPOSF2.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF3
{
	map "shaders/brightmaps/doom/CPOSF3.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF4
{
	map "shaders/brightmaps/doom/CPOSF4.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF5
{
	map "shaders/brightmaps/doom/CPOSF5.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF6
{
	map "shaders/brightmaps/doom/CPOSF6.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF7
{
	map "shaders/brightmaps/doom/CPOSF7.png"
	iwad
	disablefullbright
}

brightmap sprite CPOSF8
{
	map "shaders/brightmaps/doom/CPOSF8.png"
	iwad
	disablefullbright
}

brightmap sprite SSWVG0
{
	map "shaders/brightmaps/doom/sswvg0.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIA1D1
{
	iwad
	disablefullbright
}

brightmap sprite BSPIA2a8
{
	iwad
	disablefullbright
}

brightmap sprite BSPIA3A7
{
	iwad
	disablefullbright
}

brightmap sprite BSPIA4A6
{
	iwad
	disablefullbright
}

brightmap sprite BSPIA5D5
{
	iwad
	disablefullbright
}

brightmap sprite BSPIG1
{
	map "shaders/brightmaps/doom/bspig1.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIG2G8
{
	map "shaders/brightmaps/doom/bspig2g8.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIG3G7
{
	iwad
	disablefullbright
}

brightmap sprite BSPIG4G6
{
	iwad
	disablefullbright
}

brightmap sprite BSPIG5
{
	iwad
	disablefullbright
}

brightmap sprite BSPIH1
{
	map "shaders/brightmaps/doom/bspih1.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIH2H8
{
	map "shaders/brightmaps/doom/bspih2h8.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIH3H7
{
	map "shaders/brightmaps/doom/bspih3h7.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIH4H6
{
	map "shaders/brightmaps/doom/bspih4h6.png"
	iwad
	disablefullbright
}

brightmap sprite BSPIH5
{
	map "shaders/brightmaps/doom/bspih5.png"
	iwad
	disablefullbright
}

brightmap sprite BOSSA1
{
	map "shaders/brightmaps/doom/bossa1.png"
	iwad
}

brightmap sprite BOSSA2A8
{
	map "shaders/brightmaps/doom/bossa2a8.png"
	iwad
}

brightmap sprite BOSSA3A7
{
	map "shaders/brightmaps/doom/bossa3a7.png"
	iwad
}

brightmap sprite BOSSA4A6
{
	map "shaders/brightmaps/doom/bossa4a6.png"
	iwad
}

brightmap sprite BOSSA5
{
	map "shaders/brightmaps/doom/bossa5.png"
	iwad
}

brightmap sprite BOSSb1
{
	map "shaders/brightmaps/doom/bossb1.png"
	iwad
}

brightmap sprite BOSSB2B8
{
	map "shaders/brightmaps/doom/bossb2b8.png"
	iwad
}

brightmap sprite BOSSB3B7
{
	map "shaders/brightmaps/doom/bossb3b7.png"
	iwad
}

brightmap sprite BOSSB4B6
{
	map "shaders/brightmaps/doom/bossb4b6.png"
	iwad
}

brightmap sprite BOSSB5
{
	map "shaders/brightmaps/doom/bossb5.png"
	iwad
}

brightmap sprite BOSSC1
{
	map "shaders/brightmaps/doom/bossc1.png"
	iwad
}

brightmap sprite BOSSC2C8
{
	map "shaders/brightmaps/doom/bossc2c8.png"
	iwad
}

brightmap sprite BOSSC3C7
{
	map "shaders/brightmaps/doom/bossc3c7.png"
	iwad
}

brightmap sprite BOSSC4C6
{
	map "shaders/brightmaps/doom/bossc4c6.png"
	iwad
}

brightmap sprite BOSSC5
{
	map "shaders/brightmaps/doom/bossc5.png"
	iwad
}

brightmap sprite BOSSD1
{
	map "shaders/brightmaps/doom/bossd1.png"
	iwad
}

brightmap sprite BOSSD2D8
{
	map "shaders/brightmaps/doom/bossd2d8.png"
	iwad
}

brightmap sprite BOSSD3D7
{
	map "shaders/brightmaps/doom/bossd3d7.png"
	iwad
}

brightmap sprite BOSSD4D6
{
	map "shaders/brightmaps/doom/bossd4d6.png"
	iwad
}

brightmap sprite BOSSD5
{
	map "shaders/brightmaps/doom/bossd5.png"
	iwad
}

brightmap sprite BOSSE1
{
	map "shaders/brightmaps/doom/bosse1.png"
	iwad
}

brightmap sprite BOSSE2
{
	map "shaders/brightmaps/doom/bosse2.png"
	iwad
}

brightmap sprite BOSSE3
{
	map "shaders/brightmaps/doom/bosse3.png"
	iwad
}

brightmap sprite BOSSE4
{
	map "shaders/brightmaps/doom/bosse4.png"
	iwad
}

brightmap sprite BOSSE5
{
	map "shaders/brightmaps/doom/bosse5.png"
	iwad
}

brightmap sprite BOSSE6
{
	map "shaders/brightmaps/doom/bosse6.png"
	iwad
}

brightmap sprite BOSSE7
{
	map "shaders/brightmaps/doom/bosse7.png"
	iwad
}

brightmap sprite BOSSE8
{
	map "shaders/brightmaps/doom/bosse8.png"
	iwad
}

brightmap sprite BOSSF1
{
	map "shaders/brightmaps/doom/BOSSF1.png"
	iwad
}

brightmap sprite BOSSF2
{
	map "shaders/brightmaps/doom/BOSSF2.png"
	iwad
}

brightmap sprite BOSSF3
{
	map "shaders/brightmaps/doom/BOSSF3.png"
	iwad
}

brightmap sprite BOSSF4
{
	map "shaders/brightmaps/doom/BOSSF4.png"
	iwad
}

brightmap sprite BOSSF5
{
	map "shaders/brightmaps/doom/BOSSF5.png"
	iwad
}

brightmap sprite BOSSF6
{
	map "shaders/brightmaps/doom/BOSSF6.png"
	iwad
}

brightmap sprite BOSSF7
{
	map "shaders/brightmaps/doom/BOSSF7.png"
	iwad
}

brightmap sprite BOSSF8
{
	map "shaders/brightmaps/doom/BOSSF8.png"
	iwad
}

brightmap sprite BOSSG1
{
	map "shaders/brightmaps/doom/BOSSG1.png"
	iwad
}

brightmap sprite BOSSG2
{
	map "shaders/brightmaps/doom/BOSSG2.png"
	iwad
}

brightmap sprite BOSSG3
{
	map "shaders/brightmaps/doom/BOSSG3.png"
	iwad
}

brightmap sprite BOSSG4
{
	map "shaders/brightmaps/doom/BOSSG4.png"
	iwad
}

brightmap sprite BOSSG5
{
	map "shaders/brightmaps/doom/BOSSG5.png"
	iwad
}

brightmap sprite BOSSG6
{
	map "shaders/brightmaps/doom/BOSSG6.png"
	iwad
}

brightmap sprite BOSSG7
{
	map "shaders/brightmaps/doom/BOSSG7.png"
	iwad
}

brightmap sprite BOSSG8
{
	map "shaders/brightmaps/doom/BOSSG8.png"
	iwad
}

brightmap sprite BOSSH1
{
	map "shaders/brightmaps/doom/BOSSH1.png"
	iwad
}

brightmap sprite BOSSH2
{
	map "shaders/brightmaps/doom/BOSSH2.png"
	iwad
}

brightmap sprite BOSSH3
{
	map "shaders/brightmaps/doom/BOSSH3.png"
	iwad
}

brightmap sprite BOSSH4
{
	map "shaders/brightmaps/doom/BOSSH4.png"
	iwad
}

brightmap sprite BOSSH5
{
	map "shaders/brightmaps/doom/BOSSH5.png"
	iwad
}

brightmap sprite BOSSH6
{
	map "shaders/brightmaps/doom/BOSSH6.png"
	iwad
}

brightmap sprite BOSSH7
{
	map "shaders/brightmaps/doom/BOSSH7.png"
	iwad
}

brightmap sprite BOSSH8
{
	map "shaders/brightmaps/doom/BOSSH8.png"
	iwad
}

brightmap sprite BOSSI0
{
	map "shaders/brightmaps/doom/BOSSI0.png"
	iwad
}

brightmap sprite BOSSJ0
{
	map "shaders/brightmaps/doom/BOSSJ0.png"
	iwad
}

brightmap sprite BOSSK0
{
	map "shaders/brightmaps/doom/BOSSK0.png"
	iwad
}

brightmap sprite BOSSL0
{
	map "shaders/brightmaps/doom/BOSSL0.png"
	iwad
}

brightmap sprite BOSSM0
{
	map "shaders/brightmaps/doom/BOSSM0.png"
	iwad
}

brightmap sprite BOS2A1C1
{
	map "shaders/brightmaps/doom/bossa1.png"
	iwad
}

brightmap sprite BOS2A2C8
{
	map "shaders/brightmaps/doom/bossa2a8.png"
	iwad
}

brightmap sprite BOS2A3C7
{
	map "shaders/brightmaps/doom/bossa3a7.png"
	iwad
}

brightmap sprite BOS2A4C6
{
	map "shaders/brightmaps/doom/bossa4a6.png"
	iwad
}

brightmap sprite BOS2A5C5
{
	map "shaders/brightmaps/doom/bossa5.png"
	iwad
}

brightmap sprite BOS2b1D1
{
	map "shaders/brightmaps/doom/bossb1.png"
	iwad
}

brightmap sprite BOS2B2D8
{
	map "shaders/brightmaps/doom/bossb2b8.png"
	iwad
}

brightmap sprite BOS2B3D7
{
	map "shaders/brightmaps/doom/bossb3b7.png"
	iwad
}

brightmap sprite BOS2B4D6
{
	map "shaders/brightmaps/doom/bossb4b6.png"
	iwad
}

brightmap sprite BOS2B5D5
{
	map "shaders/brightmaps/doom/bossb5.png"
	iwad
}

brightmap sprite BOS2E1
{
	map "shaders/brightmaps/doom/bosse1.png"
	iwad
}

brightmap sprite BOS2E2
{
	map "shaders/brightmaps/doom/bosse2.png"
	iwad
}

brightmap sprite BOS2E3
{
	map "shaders/brightmaps/doom/bosse3.png"
	iwad
}

brightmap sprite BOS2E4
{
	map "shaders/brightmaps/doom/bosse4.png"
	iwad
}

brightmap sprite BOS2E5
{
	map "shaders/brightmaps/doom/bosse5.png"
	iwad
}

brightmap sprite BOS2E6
{
	map "shaders/brightmaps/doom/bosse6.png"
	iwad
}

brightmap sprite BOS2E7
{
	map "shaders/brightmaps/doom/bosse7.png"
	iwad
}

brightmap sprite BOS2E8
{
	map "shaders/brightmaps/doom/bosse8.png"
	iwad
}

brightmap sprite BOS2F1
{
	map "shaders/brightmaps/doom/BOSSF1.png"
	iwad
}

brightmap sprite BOS2F2
{
	map "shaders/brightmaps/doom/BOSSF2.png"
	iwad
}

brightmap sprite BOS2F3
{
	map "shaders/brightmaps/doom/BOSSF3.png"
	iwad
}

brightmap sprite BOS2F4
{
	map "shaders/brightmaps/doom/BOSSF4.png"
	iwad
}

brightmap sprite BOS2F5
{
	map "shaders/brightmaps/doom/BOSSF5.png"
	iwad
}

brightmap sprite BOS2F6
{
	map "shaders/brightmaps/doom/BOSSF6.png"
	iwad
}

brightmap sprite BOS2F7
{
	map "shaders/brightmaps/doom/BOSSF7.png"
	iwad
}

brightmap sprite BOS2F8
{
	map "shaders/brightmaps/doom/BOSSF8.png"
	iwad
}

brightmap sprite BOS2G1
{
	map "shaders/brightmaps/doom/BOSSG1.png"
	iwad
}

brightmap sprite BOS2G2
{
	map "shaders/brightmaps/doom/BOSSG2.png"
	iwad
}

brightmap sprite BOS2G3
{
	map "shaders/brightmaps/doom/BOSSG3.png"
	iwad
}

brightmap sprite BOS2G4
{
	map "shaders/brightmaps/doom/BOSSG4.png"
	iwad
}

brightmap sprite BOS2G5
{
	map "shaders/brightmaps/doom/BOSSG5.png"
	iwad
}

brightmap sprite BOS2G6
{
	map "shaders/brightmaps/doom/BOSSG6.png"
	iwad
}

brightmap sprite BOS2G7
{
	map "shaders/brightmaps/doom/BOSSG7.png"
	iwad
}

brightmap sprite BOS2G8
{
	map "shaders/brightmaps/doom/BOSSG8.png"
	iwad
}

brightmap sprite BOS2H1
{
	map "shaders/brightmaps/doom/BOSSH1.png"
	iwad
}

brightmap sprite BOS2H2
{
	map "shaders/brightmaps/doom/BOSSH2.png"
	iwad
}

brightmap sprite BOS2H3
{
	map "shaders/brightmaps/doom/BOSSH3.png"
	iwad
}

brightmap sprite BOS2H4
{
	map "shaders/brightmaps/doom/BOSSH4.png"
	iwad
}

brightmap sprite BOS2H5
{
	map "shaders/brightmaps/doom/BOSSH5.png"
	iwad
}

brightmap sprite BOS2H6
{
	map "shaders/brightmaps/doom/BOSSH6.png"
	iwad
}

brightmap sprite BOS2H7
{
	map "shaders/brightmaps/doom/BOSSH7.png"
	iwad
}

brightmap sprite BOS2H8
{
	map "shaders/brightmaps/doom/BOSSH8.png"
	iwad
}

brightmap sprite BOS2I0
{
	map "shaders/brightmaps/doom/BOSSI0.png"
	iwad
}

brightmap sprite BOS2J0
{
	map "shaders/brightmaps/doom/BOSSJ0.png"
	iwad
}

brightmap sprite BOS2K0
{
	map "shaders/brightmaps/doom/BOSSK0.png"
	iwad
}

brightmap sprite BOS2L0
{
	map "shaders/brightmaps/doom/BOSSL0.png"
	iwad
}

brightmap sprite BOS2M0
{
	map "shaders/brightmaps/doom/BOSSM0.png"
	iwad
}

brightmap sprite BOS2A6C4
{
	map "shaders/brightmaps/doom/BOS2A6C4.png"
	iwad
}

brightmap sprite BOS2A7C3
{
	map "shaders/brightmaps/doom/BOS2A7C3.png"
	iwad
}

brightmap sprite BOS2A8C2
{
	map "shaders/brightmaps/doom/BOS2A8C2.png"
	iwad
}

brightmap sprite BOS2B6D4
{
	map "shaders/brightmaps/doom/BOS2B6D4.png"
	iwad
}

brightmap sprite BOS2B7D3
{
	map "shaders/brightmaps/doom/BOS2B7D3.png"
	iwad
}

brightmap sprite BOS2B8D2
{
	map "shaders/brightmaps/doom/BOS2B8D2.png"
	iwad
}

brightmap sprite SKELJ1
{
	map "shaders/brightmaps/doom/SKELJ1.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ2
{
	map "shaders/brightmaps/doom/SKELJ2.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ3
{
	map "shaders/brightmaps/doom/SKELJ3.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ4
{
	map "shaders/brightmaps/doom/SKELJ4.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ5
{
	map "shaders/brightmaps/doom/SKELJ5.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ6
{
	map "shaders/brightmaps/doom/SKELJ6.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ7
{
	map "shaders/brightmaps/doom/SKELJ7.png"
	iwad
	disablefullbright
}

brightmap sprite SKELJ8
{
	map "shaders/brightmaps/doom/SKELJ8.png"
	iwad
	disablefullbright
}

brightmap sprite FATTH1
{
	map "shaders/brightmaps/doom/FATTH1.png"
	iwad
	disablefullbright
}

brightmap sprite FATTH2H8
{
	map "shaders/brightmaps/doom/FATTH2H8.png"
	iwad
	disablefullbright
}

brightmap sprite FATTH3H7
{
	map "shaders/brightmaps/doom/FATTH3H7.png"
	iwad
	disablefullbright
}

brightmap sprite FATTH4H6
{
	map "shaders/brightmaps/doom/FATTH4H6.png"
	iwad
	disablefullbright
}

brightmap sprite FATTH5
{
	map "shaders/brightmaps/doom/FATTH5.png"
	iwad
	disablefullbright
}

brightmap sprite HEADA1
{
	map "shaders/brightmaps/doom/HEADA1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADA2A8
{
	map "shaders/brightmaps/doom/HEADA2A8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADA3A7
{
	map "shaders/brightmaps/doom/HEADA3A7.png"
	iwad
	disablefullbright
}

brightmap sprite HEADB1
{
	map "shaders/brightmaps/doom/HEADB1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADB2B8
{
	map "shaders/brightmaps/doom/HEADB2B8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADB3B7
{
	map "shaders/brightmaps/doom/HEADB3B7.png"
	iwad
	disablefullbright
}

brightmap sprite HEADB4B6
{
	map "shaders/brightmaps/doom/HEADB4B6.png"
	iwad
	disablefullbright
}

brightmap sprite HEADB5
{
	map "shaders/brightmaps/doom/HEADB5.png"
	iwad
	disablefullbright
}

brightmap sprite HEADC1
{
	map "shaders/brightmaps/doom/HEADC1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADC2C8
{
	map "shaders/brightmaps/doom/HEADC2C8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADC3C7
{
	map "shaders/brightmaps/doom/HEADC3C7.png"
	iwad
	disablefullbright
}

brightmap sprite HEADC4C6
{
	map "shaders/brightmaps/doom/HEADC4C6.png"
	iwad
	disablefullbright
}

brightmap sprite HEADC5
{
	map "shaders/brightmaps/doom/HEADC5.png"
	iwad
	disablefullbright
}

brightmap sprite HEADD1
{
	map "shaders/brightmaps/doom/HEADD1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADD2D8
{
	map "shaders/brightmaps/doom/HEADD2D8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADD3D7
{
	map "shaders/brightmaps/doom/HEADD3D7.png"
	iwad
	disablefullbright
}

brightmap sprite HEADD4D6
{
	map "shaders/brightmaps/doom/HEADD4D6.png"
	iwad
	disablefullbright
}

brightmap sprite HEADD5
{
	map "shaders/brightmaps/doom/HEADD5.png"
	iwad
	disablefullbright
}

brightmap sprite HEADE1
{
	map "shaders/brightmaps/doom/HEADE1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADE2E8
{
	map "shaders/brightmaps/doom/HEADE2E8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADE3E7
{
	map "shaders/brightmaps/doom/HEADE3E7.png"
	iwad
	disablefullbright
}

brightmap sprite HEADF1
{
	map "shaders/brightmaps/doom/HEADF1.png"
	iwad
	disablefullbright
}

brightmap sprite HEADF2F8
{
	map "shaders/brightmaps/doom/HEADF2F8.png"
	iwad
	disablefullbright
}

brightmap sprite HEADF3F7
{
	map "shaders/brightmaps/doom/HEADF3F7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINA1
{
	map "shaders/brightmaps/doom/PAINA1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINA2A8
{
	map "shaders/brightmaps/doom/PAINC2C8.png"
	iwad
	disablefullbright
}

brightmap sprite PAINA3A7
{
	map "shaders/brightmaps/doom/PAINC3C7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINB1
{
	map "shaders/brightmaps/doom/PAINB1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINB2B8
{
	map "shaders/brightmaps/doom/PAINC2C8.png"
	iwad
	disablefullbright
}

brightmap sprite PAINB3B7
{
	map "shaders/brightmaps/doom/PAINC3C7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINC1
{
	map "shaders/brightmaps/doom/PAINB1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINC2C8
{
	map "shaders/brightmaps/doom/PAINC2C8.png"
	iwad
	disablefullbright
}

brightmap sprite PAINC3C7
{
	map "shaders/brightmaps/doom/PAINC3C7.png"
	iwad
	disablefullbright
}

brightmap sprite PAIND1
{
	map "shaders/brightmaps/doom/PAIND1.png"
	iwad
	disablefullbright
}

brightmap sprite PAIND2D8
{
	map "shaders/brightmaps/doom/PAIND2D8.png"
	iwad
	disablefullbright
}

brightmap sprite PAIND3D7
{
	map "shaders/brightmaps/doom/PAIND3D7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINE1
{
	map "shaders/brightmaps/doom/PAINE1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINE2E8
{
	map "shaders/brightmaps/doom/PAINE2E8.png"
	iwad
	disablefullbright
}

brightmap sprite PAINE3E7
{
	map "shaders/brightmaps/doom/PAINE3E7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINF1
{
	map "shaders/brightmaps/doom/PAINf1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINF2F8
{
	map "shaders/brightmaps/doom/PAINf2f8.png"
	iwad
	disablefullbright
}

brightmap sprite PAINF3F7
{
	map "shaders/brightmaps/doom/PAINf3f7.png"
	iwad
	disablefullbright
}

brightmap sprite PAING1
{
	map "shaders/brightmaps/doom/PAING1.png"
	iwad
	disablefullbright
}

brightmap sprite PAING2G8
{
	map "shaders/brightmaps/doom/PAING2G8.png"
	iwad
	disablefullbright
}

brightmap sprite PAING3G7
{
	map "shaders/brightmaps/doom/PAING3G7.png"
	iwad
	disablefullbright
}

brightmap sprite PAINH0
{
	map "shaders/brightmaps/doom/PAING1.png"
	iwad
	disablefullbright
}

brightmap sprite PAINI0
{
	map "shaders/brightmaps/doom/PAINI0.png"
	iwad
	disablefullbright
}

brightmap sprite PAINJ0
{
	map "shaders/brightmaps/doom/PAINJ0.png"
	iwad
	disablefullbright
}

brightmap sprite PAINK0
{
	map "shaders/brightmaps/doom/PAINK0.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRA1
{
	map "shaders/brightmaps/doom/CYBRA1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRA2
{
	map "shaders/brightmaps/doom/CYBRA2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRA3
{
	map "shaders/brightmaps/doom/CYBRA3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRA7
{
	map "shaders/brightmaps/doom/CYBRA7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRA8
{
	map "shaders/brightmaps/doom/CYBRA8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRb1
{
	map "shaders/brightmaps/doom/CYBRb1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRb2
{
	map "shaders/brightmaps/doom/CYBRb2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRb3
{
	map "shaders/brightmaps/doom/CYBRb3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRb7
{
	map "shaders/brightmaps/doom/CYBRb7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRb8
{
	map "shaders/brightmaps/doom/CYBRb8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRc1
{
	map "shaders/brightmaps/doom/CYBRc1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRc2
{
	map "shaders/brightmaps/doom/CYBRc2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRc3
{
	map "shaders/brightmaps/doom/CYBRc3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRc7
{
	map "shaders/brightmaps/doom/CYBRc7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRc8
{
	map "shaders/brightmaps/doom/CYBRc8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRd1
{
	map "shaders/brightmaps/doom/CYBRd1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRd2
{
	map "shaders/brightmaps/doom/CYBRd2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRd3
{
	map "shaders/brightmaps/doom/CYBRd3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRd7
{
	map "shaders/brightmaps/doom/CYBRd7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRd8
{
	map "shaders/brightmaps/doom/CYBRd8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRe1
{
	map "shaders/brightmaps/doom/CYBRe1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRe2
{
	map "shaders/brightmaps/doom/CYBRe2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRe3
{
	map "shaders/brightmaps/doom/CYBRe3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRe7
{
	map "shaders/brightmaps/doom/CYBRe7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRe8
{
	map "shaders/brightmaps/doom/CYBRe8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF1
{
	map "shaders/brightmaps/doom/CYBRF1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF2
{
	map "shaders/brightmaps/doom/CYBRF2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF3
{
	map "shaders/brightmaps/doom/CYBRF3.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF4
{
	map "shaders/brightmaps/doom/CYBRF4.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF5
{
	map "shaders/brightmaps/doom/CYBRF5.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF6
{
	map "shaders/brightmaps/doom/CYBRF6.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF7
{
	map "shaders/brightmaps/doom/CYBRF7.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRF8
{
	map "shaders/brightmaps/doom/CYBRF8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRg1
{
	map "shaders/brightmaps/doom/CYBRg1.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRg2
{
	map "shaders/brightmaps/doom/CYBRg2.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRg8
{
	map "shaders/brightmaps/doom/CYBRg8.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRJ0
{
	map "shaders/brightmaps/doom/CYBRJ0.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRK0
{
	map "shaders/brightmaps/doom/CYBRK0.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRL0
{
	map "shaders/brightmaps/doom/CYBRL0.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRM0
{
	map "shaders/brightmaps/doom/CYBRM0.png"
	iwad
	disablefullbright
}

brightmap sprite CYBRN0
{
	map "shaders/brightmaps/doom/CYBRN0.png"
	iwad
	disablefullbright
}

brightmap sprite MISLA1
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}


brightmap sprite MISLA5
{
	map "shaders/brightmaps/doom/MISLA5.png"
	iwad
	disablefullbright
}

brightmap sprite MISLA8A2
{
	map "shaders/brightmaps/doom/MISLA8A2.png"
	iwad
	disablefullbright
}

brightmap sprite MISLA7A3
{
	map "shaders/brightmaps/doom/MISLA7A3.png"
	iwad
	disablefullbright
}

brightmap sprite MISLA6A4
{
	map "shaders/brightmaps/doom/MISLA6A4.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDA1D1
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDA2D8
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDA3D7
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDA4D6
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDA5D5
{
	map "shaders/brightmaps/doom/MISLA1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDG1
{
	map "shaders/brightmaps/doom/SPIDG1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDG2G8
{
	map "shaders/brightmaps/doom/SPIDG2G8.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDG3G7
{
	iwad
	disablefullbright
}

brightmap sprite SPIDG4G6
{
	iwad
	disablefullbright
}

brightmap sprite SPIDG5
{
	iwad
	disablefullbright
}

brightmap sprite SPIDH1
{
	map "shaders/brightmaps/doom/SPIDH1.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDH2H8
{
	map "shaders/brightmaps/doom/SPIDH2H8.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDH3H7
{
	map "shaders/brightmaps/doom/SPIDH3H7.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDH4H6
{
	map "shaders/brightmaps/doom/SPIDH4h6.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDH5
{
	map "shaders/brightmaps/doom/SPIDH5.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDL0
{
	map "shaders/brightmaps/doom/SPIDL0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDM0
{
	map "shaders/brightmaps/doom/SPIDM0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDN0
{
	map "shaders/brightmaps/doom/SPIDN0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDO0
{
	map "shaders/brightmaps/doom/SPIDO0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDP0
{
	map "shaders/brightmaps/doom/SPIDP0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDQ0
{
	map "shaders/brightmaps/doom/SPIDQ0.png"
	iwad
	disablefullbright
}

brightmap sprite SPIDR0
{
	map "shaders/brightmaps/doom/SPIDR0.png"
	iwad
	disablefullbright
}

brightmap sprite BON2B0
{
	map "shaders/brightmaps/doom/BON2B0.png"
	iwad
	disablefullbright
}

brightmap sprite BON2c0
{
	map "shaders/brightmaps/doom/BON2c0.png"
	iwad
	disablefullbright
}

brightmap sprite BON2d0
{
	map "shaders/brightmaps/doom/BON2d0.png"
	iwad
	disablefullbright
}

brightmap sprite FCANA0
{
	map "shaders/brightmaps/doom/FCANA0.png"
	iwad
	disablefullbright
}

brightmap sprite FCANb0
{
	map "shaders/brightmaps/doom/FCANb0.png"
	iwad
	disablefullbright
}

brightmap sprite FCANc0
{
	map "shaders/brightmaps/doom/FCANc0.png"
	iwad
	disablefullbright
}

brightmap sprite treda0
{
	map "shaders/brightmaps/doom/treda0.png"
	iwad
	disablefullbright
}

brightmap sprite tredb0
{
	map "shaders/brightmaps/doom/tredb0.png"
	iwad
	disablefullbright
}

brightmap sprite tredc0
{
	map "shaders/brightmaps/doom/tredc0.png"
	iwad
	disablefullbright
}

brightmap sprite tredd0
{
	map "shaders/brightmaps/doom/tredd0.png"
	iwad
	disablefullbright
}

brightmap sprite TBLUA0
{
	map "shaders/brightmaps/doom/treda0.png"
	iwad
	disablefullbright
}

brightmap sprite TBLUb0
{
	map "shaders/brightmaps/doom/TBLUb0.png"
	iwad
	disablefullbright
}

brightmap sprite TBLUc0
{
	map "shaders/brightmaps/doom/TBLUc0.png"
	iwad
	disablefullbright
}

brightmap sprite TBLUd0
{
	map "shaders/brightmaps/doom/tredd0.png"
	iwad
	disablefullbright
}

brightmap sprite TGRNA0
{
	map "shaders/brightmaps/doom/treda0.png"
	iwad
	disablefullbright
}

brightmap sprite TGRNb0
{
	map "shaders/brightmaps/doom/tredb0.png"
	iwad
	disablefullbright
}

brightmap sprite TGRNc0
{
	map "shaders/brightmaps/doom/tredc0.png"
	iwad
	disablefullbright
}

brightmap sprite TGRNd0
{
	map "shaders/brightmaps/doom/tredd0.png"
	iwad
	disablefullbright
}

brightmap sprite SMRTA0
{
	map "shaders/brightmaps/doom/SMRTA0.png"
	iwad
	disablefullbright
}

brightmap sprite SMRTb0
{
	map "shaders/brightmaps/doom/SMRTb0.png"
	iwad
	disablefullbright
}

brightmap sprite SMRTc0
{
	map "shaders/brightmaps/doom/SMRTc0.png"
	iwad
	disablefullbright
}

brightmap sprite SMRTd0
{
	map "shaders/brightmaps/doom/SMRTd0.png"
	iwad
	disablefullbright
}

brightmap sprite SMbTA0
{
	map "shaders/brightmaps/doom/SMRTA0.png"
	iwad
	disablefullbright
}

brightmap sprite SMbTb0
{
	map "shaders/brightmaps/doom/SMRTb0.png"
	iwad
	disablefullbright
}

brightmap sprite SMbTc0
{
	map "shaders/brightmaps/doom/SMRTc0.png"
	iwad
	disablefullbright
}

brightmap sprite SMbTd0
{
	map "shaders/brightmaps/doom/SMRTd0.png"
	iwad
	disablefullbright
}

brightmap sprite SMgTA0
{
	map "shaders/brightmaps/doom/SMRTA0.png"
	iwad
	disablefullbright
}

brightmap sprite SMgTb0
{
	map "shaders/brightmaps/doom/SMRTb0.png"
	iwad
	disablefullbright
}

brightmap sprite SMgTc0
{
	map "shaders/brightmaps/doom/SMRTc0.png"
	iwad
	disablefullbright
}

brightmap sprite SMgTd0
{
	map "shaders/brightmaps/doom/SMRTd0.png"
	iwad
	disablefullbright
}

brightmap sprite SARGA1
{
   map "shaders/brightmaps/doom/SARGA1.png"
   iwad
}

brightmap sprite SARGA2A8
{
   map "shaders/brightmaps/doom/SARGA2A8.png"
   iwad
}   

brightmap sprite SARGA3A7
{
   map "shaders/brightmaps/doom/SARGA3A7.png"
   iwad
}   

brightmap sprite SARGB1
{
   map "shaders/brightmaps/doom/SARGB1.png"
   iwad
}   

brightmap sprite SARGB2B8
{
   map "shaders/brightmaps/doom/SARGB2B8.png"
   iwad
}  

brightmap sprite SARGB3B7
{
   map "shaders/brightmaps/doom/SARGB3B7.png"
   iwad
} 

brightmap sprite SARGC1
{
   map "shaders/brightmaps/doom/SARGC1.png"
   iwad
}

brightmap sprite SARGC2C8
{
   map "shaders/brightmaps/doom/SARGC2C8.png"
   iwad
}   

brightmap sprite SARGC3C7
{
   map "shaders/brightmaps/doom/SARGC3C7.png"
   iwad
}   

brightmap sprite SARGD1
{
   map "shaders/brightmaps/doom/SARGD1.png"
   iwad
}   

brightmap sprite SARGD2D8
{
   map "shaders/brightmaps/doom/SARGD2D8.png"
   iwad
}  

brightmap sprite SARGD3D7
{
   map "shaders/brightmaps/doom/SARGD3D7.png"
   iwad
}

brightmap sprite SARGE1
{
   map "shaders/brightmaps/doom/SARGE1.png"
   iwad
}    

brightmap sprite SARGE2
{
   map "shaders/brightmaps/doom/SARGE2.png"
   iwad
}

brightmap sprite SARGE3
{
   map "shaders/brightmaps/doom/SARGE3.png"
   iwad
} 

brightmap sprite SARGE7
{
   map "shaders/brightmaps/doom/SARGE7.png"
   iwad
}     

brightmap sprite SARGE8
{
   map "shaders/brightmaps/doom/SARGE8.png"
   iwad
} 

brightmap sprite SARGF1
{
   map "shaders/brightmaps/doom/SARGF1.png"
   iwad
}    

brightmap sprite SARGF2
{
   map "shaders/brightmaps/doom/SARGF2.png"
   iwad
}

brightmap sprite SARGF3
{
   map "shaders/brightmaps/doom/SARGF3.png"
   iwad
} 

brightmap sprite SARGF7
{
   map "shaders/brightmaps/doom/SARGF7.png"
   iwad
}     

brightmap sprite SARGF8
{
   map "shaders/brightmaps/doom/SARGF8.png"
   iwad
} 

brightmap sprite SARGG1
{
   map "shaders/brightmaps/doom/SARGG1.png"
   iwad
}    

brightmap sprite SARGG2
{
   map "shaders/brightmaps/doom/SARGG2.png"
   iwad
}

brightmap sprite SARGG3
{
   map "shaders/brightmaps/doom/SARGG3.png"
   iwad
} 

brightmap sprite SARGG7
{
   map "shaders/brightmaps/doom/SARGG7.png"
   iwad
}     

brightmap sprite SARGG8
{
   map "shaders/brightmaps/doom/SARGG8.png"
   iwad
}

brightmap sprite SARGH1
{
   map "shaders/brightmaps/doom/SARGH1.png"
   iwad
}    

brightmap sprite SARGH2
{
   map "shaders/brightmaps/doom/SARGH2.png"
   iwad
}

brightmap sprite SARGH3
{
   map "shaders/brightmaps/doom/SARGH3.png"
   iwad
} 

brightmap sprite SARGH4
{
   map "shaders/brightmaps/doom/SARGH4.png"
   iwad
}     

brightmap sprite SARGH8
{
   map "shaders/brightmaps/doom/SARGH8.png"
   iwad
}  

brightmap sprite vileg1
{
  map "shaders/brightmaps/doom/vileg1.png"
  iwad
  disablefullbright
}

brightmap sprite vileg2
{
  map "shaders/brightmaps/doom/vileg2.png"
  iwad
  disablefullbright
}

brightmap sprite vileg3
{
  map "shaders/brightmaps/doom/vileg3.png"
  iwad
  disablefullbright
}

brightmap sprite vileg4
{
  map "shaders/brightmaps/doom/vileg4.png"
  iwad
  disablefullbright
}

brightmap sprite vileg5
{
  map "shaders/brightmaps/doom/vileg5.png"
  iwad
  disablefullbright
}

brightmap sprite vileg6
{
  map "shaders/brightmaps/doom/vileg6.png"
  iwad
  disablefullbright
}

brightmap sprite vileg7
{
  map "shaders/brightmaps/doom/vileg7.png"
  iwad
  disablefullbright
}

brightmap sprite vileg8
{
  map "shaders/brightmaps/doom/vileg8.png"
  iwad
  disablefullbright
}

brightmap sprite vileh1
{
  map "shaders/brightmaps/doom/vileh1.png"
  iwad
  disablefullbright
}

brightmap sprite vileh2
{
  map "shaders/brightmaps/doom/vileh2.png"
  iwad
  disablefullbright
}

brightmap sprite vileh3
{
  map "shaders/brightmaps/doom/vileh3.png"
  iwad
  disablefullbright
}

brightmap sprite vileh4
{
  map "shaders/brightmaps/doom/vileh4.png"
  iwad
  disablefullbright
}

brightmap sprite vileh5
{
  map "shaders/brightmaps/doom/vileh5.png"
  iwad
  disablefullbright
}

brightmap sprite vileh6
{
  map "shaders/brightmaps/doom/vileh6.png"
  iwad
  disablefullbright
}

brightmap sprite vileh7
{
  map "shaders/brightmaps/doom/vileh7.png"
  iwad
  disablefullbright
}

brightmap sprite vileh8
{
  map "shaders/brightmaps/doom/vileh8.png"
  iwad
  disablefullbright
}

brightmap sprite vilei1
{
  map "shaders/brightmaps/doom/vilei1.png"
  iwad
  disablefullbright
}

brightmap sprite vilei2
{
  map "shaders/brightmaps/doom/vilei2.png"
  iwad
  disablefullbright
}

brightmap sprite vilei3
{
  map "shaders/brightmaps/doom/vilei3.png"
  iwad
  disablefullbright
}

brightmap sprite vilei4
{
  map "shaders/brightmaps/doom/vilei4.png"
  iwad
  disablefullbright
}

brightmap sprite vilei5
{
  map "shaders/brightmaps/doom/vilei5.png"
  iwad
  disablefullbright
}

brightmap sprite vilei6
{
  map "shaders/brightmaps/doom/vilei6.png"
  iwad
  disablefullbright
}

brightmap sprite vilei7
{
  map "shaders/brightmaps/doom/vilei7.png"
  iwad
  disablefullbright
}

brightmap sprite vilei8
{
  map "shaders/brightmaps/doom/vilei8.png"
  iwad
  disablefullbright
}

brightmap sprite vilej1
{
  map "shaders/brightmaps/doom/vilej1.png"
  iwad
  disablefullbright
}

brightmap sprite vilej2
{
  map "shaders/brightmaps/doom/vilej2.png"
  iwad
  disablefullbright
}

brightmap sprite vilej3
{
  map "shaders/brightmaps/doom/vilej3.png"
  iwad
  disablefullbright
}

brightmap sprite vilej4
{
  map "shaders/brightmaps/doom/vilej4.png"
  iwad
  disablefullbright
}

brightmap sprite vilej5
{
  map "shaders/brightmaps/doom/vilej5.png"
  iwad
  disablefullbright
}

brightmap sprite vilej6
{
  map "shaders/brightmaps/doom/vilej6.png"
  iwad
  disablefullbright
}

brightmap sprite vilej7
{
  map "shaders/brightmaps/doom/vilej7.png"
  iwad
  disablefullbright
}

brightmap sprite vilej8
{
  map "shaders/brightmaps/doom/vilej8.png"
  iwad
  disablefullbright
}

brightmap sprite vilek1
{
  map "shaders/brightmaps/doom/vilek1.png"
  iwad
  disablefullbright
}

brightmap sprite vilek2
{
  map "shaders/brightmaps/doom/vilek2.png"
  iwad
  disablefullbright
}

brightmap sprite vilek3
{
  map "shaders/brightmaps/doom/vilek3.png"
  iwad
  disablefullbright
}

brightmap sprite vilek4
{
  map "shaders/brightmaps/doom/vilek4.png"
  iwad
  disablefullbright
}

brightmap sprite vilek5
{
  map "shaders/brightmaps/doom/vilek5.png"
  iwad
  disablefullbright
}

brightmap sprite vilek6
{
  map "shaders/brightmaps/doom/vilek6.png"
  iwad
  disablefullbright
}

brightmap sprite vilek7
{
  map "shaders/brightmaps/doom/vilek7.png"
  iwad
  disablefullbright
}

brightmap sprite vilek8
{
  map "shaders/brightmaps/doom/vilek8.png"
  iwad
  disablefullbright
}

brightmap sprite vilel1
{
  map "shaders/brightmaps/doom/vilel1.png"
  iwad
  disablefullbright
}

brightmap sprite vilel2
{
  map "shaders/brightmaps/doom/vilel2.png"
  iwad
  disablefullbright
}

brightmap sprite vilel3
{
  map "shaders/brightmaps/doom/vilel3.png"
  iwad
  disablefullbright
}

brightmap sprite vilel4
{
  map "shaders/brightmaps/doom/vilel4.png"
  iwad
  disablefullbright
}

brightmap sprite vilel5
{
  map "shaders/brightmaps/doom/vilel5.png"
  iwad
  disablefullbright
}

brightmap sprite vilel6
{
  map "shaders/brightmaps/doom/vilel6.png"
  iwad
  disablefullbright
}

brightmap sprite vilel7
{
  map "shaders/brightmaps/doom/vilel7.png"
  iwad
  disablefullbright
}

brightmap sprite vilel8
{
  map "shaders/brightmaps/doom/vilel8.png"
  iwad
  disablefullbright
}

brightmap sprite vilem1
{
  map "shaders/brightmaps/doom/vilem1.png"
  iwad
  disablefullbright
}

brightmap sprite vilem2
{
  map "shaders/brightmaps/doom/vilem2.png"
  iwad
  disablefullbright
}

brightmap sprite vilem3
{
  map "shaders/brightmaps/doom/vilem3.png"
  iwad
  disablefullbright
}

brightmap sprite vilem4
{
  map "shaders/brightmaps/doom/vilem4.png"
  iwad
  disablefullbright
}

brightmap sprite vilem5
{
  map "shaders/brightmaps/doom/vilem5.png"
  iwad
  disablefullbright
}

brightmap sprite vilem6
{
  map "shaders/brightmaps/doom/vilem6.png"
  iwad
  disablefullbright
}

brightmap sprite vilem7
{
  map "shaders/brightmaps/doom/vilem7.png"
  iwad
  disablefullbright
}

brightmap sprite vilem8
{
  map "shaders/brightmaps/doom/vilem8.png"
  iwad
  disablefullbright
}

brightmap sprite vilen1
{
  map "shaders/brightmaps/doom/vilen1.png"
  iwad
  disablefullbright
}

brightmap sprite vilen2
{
  map "shaders/brightmaps/doom/vilen2.png"
  iwad
  disablefullbright
}

brightmap sprite vilen3
{
  map "shaders/brightmaps/doom/vilen3.png"
  iwad
  disablefullbright
}

brightmap sprite vilen4
{
  map "shaders/brightmaps/doom/vilen4.png"
  iwad
  disablefullbright
}

brightmap sprite vilen5
{
  map "shaders/brightmaps/doom/vilen5.png"
  iwad
  disablefullbright
}

brightmap sprite vilen6
{
  map "shaders/brightmaps/doom/vilen6.png"
  iwad
  disablefullbright
}

brightmap sprite vilen7
{
  map "shaders/brightmaps/doom/vilen7.png"
  iwad
  disablefullbright
}

brightmap sprite vilen8
{
  map "shaders/brightmaps/doom/vilen8.png"
  iwad
  disablefullbright
}

brightmap sprite vileo1
{
  map "shaders/brightmaps/doom/vileo1.png"
  iwad
  disablefullbright
}

brightmap sprite vileo2
{
  map "shaders/brightmaps/doom/vileo2.png"
  iwad
  disablefullbright
}

brightmap sprite vileo3
{
  map "shaders/brightmaps/doom/vileo3.png"
  iwad
  disablefullbright
}

brightmap sprite vileo4
{
  map "shaders/brightmaps/doom/vileo4.png"
  iwad
  disablefullbright
}

brightmap sprite vileo5
{
  map "shaders/brightmaps/doom/vileo5.png"
  iwad
  disablefullbright
}

brightmap sprite vileo6
{
  map "shaders/brightmaps/doom/vileo6.png"
  iwad
  disablefullbright
}

brightmap sprite vileo7
{
  map "shaders/brightmaps/doom/vileo7.png"
  iwad
  disablefullbright
}

brightmap sprite vileo8
{
  map "shaders/brightmaps/doom/vileo8.png"
  iwad
  disablefullbright
}

brightmap sprite vilep1
{
  map "shaders/brightmaps/doom/vilep1.png"
  iwad
  disablefullbright
}

brightmap sprite vilep2
{
  map "shaders/brightmaps/doom/vilep2.png"
  iwad
  disablefullbright
}

brightmap sprite vilep3
{
  map "shaders/brightmaps/doom/vilep3.png"
  iwad
  disablefullbright
}

brightmap sprite vilep4
{
  map "shaders/brightmaps/doom/vilep4.png"
  iwad
  disablefullbright
}

brightmap sprite vilep5
{
  map "shaders/brightmaps/doom/vilep5.png"
  iwad
  disablefullbright
}

brightmap sprite vilep6
{
  map "shaders/brightmaps/doom/vilep6.png"
  iwad
  disablefullbright
}

brightmap sprite vilep7
{
  map "shaders/brightmaps/doom/vilep7.png"
  iwad
  disablefullbright
}

brightmap sprite vilep8
{
  map "shaders/brightmaps/doom/vilep8.png"
  iwad
  disablefullbright
}

brightmap texture bigbrik3
{
  map "shaders/brightmaps/doom/bigbrik3.png"
  iwad
}

brightmap texture bricklit
{
  map "shaders/brightmaps/doom/bricklit.png"
  iwad
}  

brightmap texture bronze4
{
  map "shaders/brightmaps/doom/bigbrik3.png"
  iwad
}

brightmap texture bstone3
{
  map "shaders/brightmaps/doom/bstone3.png"
  iwad
}

brightmap texture CRACKLe2
{
  map "shaders/brightmaps/doom/CRACKLe2.png"
  iwad
}

brightmap texture CRACKLe4
{
  map "shaders/brightmaps/doom/CRACKLe2.png"
  iwad
}

brightmap texture metal3
{
  map "shaders/brightmaps/doom/metal3.png"
  iwad
}

brightmap texture metal6
{
  map "shaders/brightmaps/doom/metal6.png"
  iwad
}

brightmap texture metal7
{
  map "shaders/brightmaps/doom/metal7.png"
  iwad
}

brightmap texture panbook
{
  map "shaders/brightmaps/doom/panbook.png"
  iwad
}

brightmap texture pipewal1
{
  map "shaders/brightmaps/doom/pipewall1.png"
  iwad
}

brightmap texture silver2
{
  map "shaders/brightmaps/doom/silver2.png"
  iwad
}

brightmap texture silver3
{
  map "shaders/brightmaps/doom/silver3.png"
  iwad
}

brightmap texture spacew3
{
  map "shaders/brightmaps/doom/spacew3.png"
  iwad
}

brightmap texture spcdoor1
{
  map "shaders/brightmaps/doom/spcdoor1.png"
  iwad
}

brightmap texture spcdoor2
{
  map "shaders/brightmaps/doom/spcdoor1.png"
  iwad
}

brightmap texture spcdoor3
{
  map "shaders/brightmaps/doom/spcdoor3.png"
  iwad
}

brightmap texture spcdoor4
{
  map "shaders/brightmaps/doom/spcdoor4.png"
  iwad
}

brightmap texture sw1met2
{
  map "shaders/brightmaps/doom/sw1met2.png"
  iwad
}

brightmap texture sw1starg
{
  map "shaders/brightmaps/doom/sw1brcom.png"
  iwad
}

brightmap texture sw1brn1
{
  map "shaders/brightmaps/doom/sw1brcom.png"
  iwad
}

brightmap texture sw1brik
{
  map "shaders/brightmaps/doom/sw1brik.png"
  iwad
}

brightmap texture sw1wdmet
{
  map "shaders/brightmaps/doom/sw1wdmet.png"
  iwad
}

brightmap texture sw2brik
{
  map "shaders/brightmaps/doom/sw1wdmet.png"
  iwad
}

brightmap texture sw2brn1
{
  map "shaders/brightmaps/doom/sw2brcom.png"
  iwad
}

brightmap texture sw2marb
{
  map "shaders/brightmaps/doom/sw2marb.png"
  iwad
}

brightmap texture sw2met2
{
  map "shaders/brightmaps/doom/sw2met2.png"
  iwad
}

brightmap texture sw2mod1
{
  map "shaders/brightmaps/doom/sw2mod1.png"
  iwad
}

brightmap texture sw2panel
{
  map "shaders/brightmaps/doom/sw2panel.png"
  iwad
}

brightmap texture sw2rock
{
  map "shaders/brightmaps/doom/sw2rock.png"
  iwad
}

brightmap texture sw2skull
{
  map "shaders/brightmaps/doom/sw2skull.png"
  iwad
}

brightmap texture sw2starg
{
  map "shaders/brightmaps/doom/sw2brcom.png"
  iwad
}

brightmap texture sw2brn1
{
  map "shaders/brightmaps/doom/sw2brcom.png"
  iwad
}

brightmap texture sw2ston6
{
  map "shaders/brightmaps/doom/sw2ston6.png"
  iwad
}

brightmap texture sw2tek
{
  map "shaders/brightmaps/doom/sw2tek.png"
  iwad
}

brightmap texture sw2wdmet
{
  map "shaders/brightmaps/doom/sw1wdmet.png"
  iwad
}

brightmap texture sw2zim
{
  map "shaders/brightmaps/doom/sw2zim.png"
  iwad
}

brightmap texture tekbron2
{
  map "shaders/brightmaps/doom/tekbron2.png"
  iwad
}

brightmap texture tekgren1
{
  map "shaders/brightmaps/doom/tekgren1.png"
  iwad
}

brightmap texture tekgren3
{
  map "shaders/brightmaps/doom/tekgren3.png"
  iwad
}

brightmap texture tekgren5
{
  map "shaders/brightmaps/doom/tekgren5.png"
  iwad
}

brightmap texture teklite
{
  map "shaders/brightmaps/doom/teklite.png"
  iwad
}

brightmap texture teklite2
{
  map "shaders/brightmaps/doom/teklite2.png"
  iwad
}

brightmap texture tekwall6
{
  map "shaders/brightmaps/doom/tekwall6.png"
  iwad
}

